cc_binary(
        name='server',
        srcs=['server.cpp'],
        deps =[
        '//thirdparty/boost:boost_system',
        '//thirdparty/boost:boost_thread',
        '//thirdparty/boost:boost_filesystem',
        '//thirdparty/boost:boost_date_time',
        '//thirdparty/event:event',
        '#pthread'
        ],
       )
