/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "debug";
extern const char kBuildTime[] = "Sat Jul 25 15:54:09 2015";
extern const char kBuilderName[] = "liuchao";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.8.3";
}}
